---
title: "p8105_hw5_gl2677"
author: "Gaotong LIU"
date: "11/3/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	message = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_bw() + theme(legend.position = "bottom"))
```

## Problem 1
```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species)) 

missing_fill = function(x) {
  if (is.numeric(x)) {
    mean = mean(x, na.rm = TRUE)
    x = replace_na(x, mean) %>% round(digits = 1)
  } else if (is.character(x)) {
    x = replace_na(x, "virginica")
  }
  return(x)
}

map(iris_with_missing, missing_fill) 
```

## Problem 2
```{r}
df =
  tibble(file_names = list.files("data/"),
         path = str_c("data/", list.files("data/"))) %>%
  mutate(observation = map(path, read_csv)) %>% 
  mutate(file_names = str_replace(file_names, ".csv", "")) %>% 
  separate(file_names, into = c("group", "id"), remove = FALSE) %>% 
  select(-path) %>% 
  unnest() %>% 
  pivot_longer(week_1:week_8,
               names_prefix = "week_",
               names_to = "week",
               values_to = "value")

df %>% 
  ggplot(aes(x = week, y = value, color = group)) + 
  geom_point() + 
  geom_line(aes(group = file_names)) +
  labs(title = "Spaghetti plot of observations on each subject over time")
```

* The value in control group fluctuates bewteen `r df %>% filter(group  == "con") %>% pull(value) %>% max()` and `r df %>% filter(group  == "con") %>% pull(value) %>% min()` over eight weeks. 

* The value in experiment group gradually increases over eight weeks. The mean value increases from `r df %>% filter(group  == "exp" & week == "1") %>% pull(value) %>% mean()`in week 1 to `r df %>% filter(group  == "exp" & week == "8") %>% pull(value) %>% mean()` in week 8. 


